spring:
    datasource:
        url: jdbc:mysql://localhost:3306/home?serverTimezone=UTC&amp&characterEncoding=UTF-8
        characterEncoding: UTF-8
        username: root
        password: '{cipher}4af388bdf01aae977810550596852df606480d490ec4f00b3da7b7ff29194184'
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
jwt:
    secret_key: 123jh124kjlfkjafdasdfasdflkjkldkajsdkjdfjhasdjflksjdflkjsdlfakjskjklfdjkajdkajdskfjkf
    expTime: 86400000
