test:
  name: pcomment
  content: testing
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcomment?serverTimezone=UTC&amp&characterEncoding=UTF-8
    characterEncoding: UTF-8
    username: root
    password: "{cipher}f60ea11dfd6b2dfdc70523d97636894beaae43e55daa26b9ed73e62936a90c74"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret_key: 123jh124kjlfkjafdasdfasdflkjkldkajsdkjdfjhasdjflksjdflkjsdlfakjskjklfdjkajdkajdskfjkf
  expTime: 86400000
