posco:
  name: pcomment
  count: 20212323
datasource:
  url: jdbc:mysql://localhost:3306/pcomment?serverTimezone=UTC&amp&characterEncoding=UTF-8
  username: root
  password: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pcomment?serverTimezone=UTC&amp&characterEncoding=UTF-8
    characterEncoding: UTF-8
    username: root
    password: "{cipher}aef47b74a38f0bc9fb504cf7928b813b529bbd3bbd5ade4fc1711f8a7b1a5938"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret_key: 123jh124kjlfkjafdasdfasdflkjkldkajsdkjdfjhasdjflksjdflkjsdlfakjskjklfdjkajdkajdskfjkf
  expTime: 86400000
